"""empty message

Revision ID: 3d7141fd82fa
Revises: 15367d9f26a3
Create Date: 2024-08-04 21:41:39.951783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7141fd82fa'
down_revision: Union[str, None] = '15367d9f26a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'order_details', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'order_id')
    # ### end Alembic commands ###
