"""empty message

Revision ID: 60a29536df2e
Revises: 3d7141fd82fa
Create Date: 2024-08-04 23:06:37.616564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a29536df2e'
down_revision: Union[str, None] = '3d7141fd82fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('headline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'headline')
    # ### end Alembic commands ###
