"""empty message

Revision ID: bfea0c79a944
Revises: e350f37f16ab
Create Date: 2024-08-04 09:06:12.852618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfea0c79a944'
down_revision: Union[str, None] = 'e350f37f16ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_details', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('payment_status', postgresql.ENUM('pending', 'completed', 'cancelled', name='statusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
